### ISSUE TITLE
the issues of environment.yml file

### ISSUE THREAD

**Issue by ZenghuiZou** [AI-HPC-Research-Team/Space_signal_detection_all4#2]
When I run conda env create -f environment.yml  one warning and one error appear:

1) The warning:
'Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.'
I fixed this by adding a line '-pip' before the line  '- pip:' in the file

2) the error:
CondaValueError: prefix already exists: C:\Users\Nemo\Anaconda3
I fixed this problem by renaming the environment name ( on the first line in the file). Previously it was 'name: base'. I already have an environment named base in my Anaconda, so the name conflicts. 

After I fixed these there is a new issue happened:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - python-lalsimulation==3.0.0=py38hff97c14_2
  - python-lal==7.1.3=fftw_py38h916f30c_104
  - python-ligo-lw==1.7.1=py38h497a2fe_2
  - python-lalinspiral==2.0.3=py38h6c62de6_0
  - ligo-segments==1.4.0=py38h497a2fe_1
  - numba==0.52.0=py38h51da96c_0
  - lalsimulation==3.0.0=py38haea4125_2
  - python-lalmetaio==2.0.3=py38h6c62de6_0
  - ligo.skymap==0.6.0=py38h1e9c115_0
  - pycbc==1.16.11=py38he5e4c54_1
  - astropy-healpix==0.6=py38h6c62de6_1
  - python-lalframe==1.5.5=py38hff97c14_1
  - python-lalburst==1.5.9=py38hb2fb00f_1
  - python-libarchive-c==3.1=py38h578d9bd_0
  - python==3.8.10=h49503c6_1_cpython
  - hdf5==1.12.1=nompi_h2750804_100
  - h5py==3.6.0=nompi_py38hfbb2109_100

Could anyone help me to solve this issue? 
Thank you!

Zenghui

**Comment by ZenghuiZou** [comment]
I have tried the mac_env.yml on my Mac.  At beginning, the pip dependencies could not be installed successfully.  It seems the  'pip subprocess' problem. Then I tried to update my Conda, but an issue happened. It mentioned that:
'RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.'
Then I solved this issue by running following two commands:
conda update --force -n base -c defaults conda
conda update -n base -c defaults conda.

After the conda was successfully installed, the pip  dependencies in the .yml file can be installed successfully.

**Comment by Zhaoty96** [comment]
Could you try manually installing the pip packages? Also, can you give more info on the 'pip subprocess' problem? By the way, no need to update your conda – the issue seems to be with pip.

**Comment by ZenghuiZou** [comment]
Hi,

   Thanks for your reply.
   I did not try manually installing the pip packages, because I have
solved the conda updating problem and then all the pip packages can be
installed via ylm file. In case you are interested in the error, I
attach a .txt file describing the error. you will find that the 'Pip
subprocess error:' issue starts from lime 59.


Best Wishes
Zenghui







> Could you try manually installing the pip packages? Also, can you give
> more info on the 'pip subprocess' problem? By the way, no need to update
> your conda – the issue seems to be with pip.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/AI-HPC-Research-Team/Space_signal_detection_all4/issues/2#issuecomment-1720485040
> You are receiving this because you authored the thread.
>
> Message ID:
> ***@***.***>

------=_20230915063244_23181
Content-Type: text/plain; name="errors.txt"
Content-Transfer-Encoding: 8bit
Content-Disposition: attachment; filename="errors.txt"

(base) ***@***.*** GW % conda env create -f mac_env.yml

EnvironmentFileNotFound: '/Users/Zou/Desktop/GW/mac_env.yml' file not found

(base) ***@***.*** GW % cd space_signal_detection_all4
(base) ***@***.*** space_signal_detection_all4 % conda env create -f mac_env.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.3
  latest version: 23.7.4

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.4



Downloading and Extracting Packages
                                                                                                                     
Preparing transaction: done                                                                                          
Verifying transaction: done                                                                                          
Executing transaction: done                                                                                          
Installing pip dependencies: \ Ran pip subprocess with arguments:                                                    
['/Users/Zou/opt/miniconda3/envs/test/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt', '--exists-action=b']                                       
Pip subprocess output:                                                                                               
Requirement already satisfied: astropy in /Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 1)) (5.2.2)                 
Collecting flake8 (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 2))                                                                                                                 
  Obtaining dependency information for flake8 from https://files.pythonhosted.org/packages/b0/24/bbf7175ffc47cb3d3e1eb523ddb23272968359dfcf2e1294707a2bf12fc4/flake8-6.1.0-py2.py3-none-any.whl.metadata                                  
  Using cached flake8-6.1.0-py2.py3-none-any.whl.metadata (3.8 kB)                                                   
Requirement already satisfied: matplotlib in /Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 3)) (3.7.1)              
Collecting matplotlib (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 3))                                                                                                             
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/cd/be/c3185d7a90460e63c84e3f8eac75692174f0a91a889403948bff609fce53/matplotlib-3.7.3-cp38-cp38-macosx_10_12_x86_64.whl.metadata             
  Downloading matplotlib-3.7.3-cp38-cp38-macosx_10_12_x86_64.whl.metadata (5.7 kB)                                   
Requirement already satisfied: numpy in /Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 4)) (1.24.4)                  
Collecting pandas (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 5))                                                                                                                 
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/78/a8/07dd10f90ca915ed914853cd57f79bfc22e1ef4384ab56cb4336d2fc1f2a/pandas-2.0.3-cp38-cp38-macosx_10_9_x86_64.whl.metadata                      
  Downloading pandas-2.0.3-cp38-cp38-macosx_10_9_x86_64.whl.metadata (18 kB)                                         
Collecting psd (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 6))                                                                                                                    
  Using cached psd-1.5.2.tar.gz (6.8 kB)                                                                             
  Preparing metadata (setup.py): started                                                                             
  Preparing metadata (setup.py): finished with status 'done'                                                         
Collecting pycbc (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 7))                                                                                                                  
  Obtaining dependency information for pycbc from https://files.pythonhosted.org/packages/98/b9/d518487ffd8cb942bc4f7713ce83b4c08e9375fbb1493d134aba3c5546b5/PyCBC-2.2.2-cp38-cp38-macosx_10_9_x86_64.whl.metadata                        
  Downloading PyCBC-2.2.2-cp38-cp38-macosx_10_9_x86_64.whl.metadata (4.4 kB)                                         
Collecting rich (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 8))
  Obtaining dependency information for rich from https://files.pythonhosted.org/packages/8d/5f/21a93b2ec205f4b79853ff6e838e3c99064d5dbe85ec6b05967506f14af0/rich-13.5.2-py3-none-any.whl.metadata
  Using cached rich-13.5.2-py3-none-any.whl.metadata (18 kB)
Collecting scikit-learn (from -r /Users/Zou/Desktop/GW/space_signal_detection_all4/condaenv.rt1v6t9a.requirements.txt (line 9))
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/33/cb/0e41fad5b30fd66925e47952ddc720d078bdfd8397584a4873ec1cf590ca/scikit_learn-1.3.0-cp38-cp38-macosx_10_9_x86_64.whl.metadata
  Downloading scikit_learn-1.3.0-cp38-cp38-macosx_10_9_x86_64.whl.metadata (11 kB)

Pip subprocess error:
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f874ca1e190>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/cd/be/c3185d7a90460e63c84e3f8eac75692174f0a91a889403948bff609fce53/matplotlib-3.7.3-cp38-cp38-macosx_10_12_x86_64.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f874ca1e430>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/cd/be/c3185d7a90460e63c84e3f8eac75692174f0a91a889403948bff609fce53/matplotlib-3.7.3-cp38-cp38-macosx_10_12_x86_64.whl.metadata
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/http/client.py", line 455, in read
    n = self.readinto(b)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/http/client.py", line 499, in readinto
    n = self.fp.readinto(b)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 532, in prepare_linked_requirement
    metadata_dist = self._fetch_metadata_only(req)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 383, in _fetch_metadata_only
    return self._fetch_metadata_using_link_data_attr(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 403, in _fetch_metadata_using_link_data_attr
    metadata_file = get_http_url(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/Zou/opt/miniconda3/envs/test/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

failed

CondaEnvException: Pip failed
------=_20230915063244_23181--
